server:
  port: 8021
  tomcat:
    max-swallow-size: -1 # 비동기 요청 Body의 최대 크기에 대한 값을 -1 로 주어, 사용자 정의 예외처리를 구현하도록 한다.(핵심 설정)
#  servlet:
#    context-path: /untact # ContextPath must start with '/' and not end with '/'


# 문서 기본 경로(v2/api-docs) 변경 시: v1, v3 도 같은 패턴으로 변경 가능, 프로퍼티명은 InMemorySwaggerResourcesProvider 소스코드 참조
springfox:
  documentation:
    swagger:
      v2:
        path: /my/api-docs

spring:
  servlet:
    multipart:
      max-file-size: 10MB # 전송되는 개별 파일의 크기 제한 : 한 파일이 가질 수 있는 크기
      max-request-size: 10MB # 서버측으로 전송된 요청(request) 자체의 크기 제한 : 모든 파일의 크기를 합한 값
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3308/untact2021?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
#     Log4j2 JDBC SQL Logger 출력
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3308/untact2021?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: untact2021
    password: 123456A@

mybatis:
  # mybatis 매핑 type을 짧게 쓰기 위한 설정
  type-aliases-package: com.tena.untact2021.dto
#  mapper-locations:
#  - classpath:mybatis/mapper/*.xml

logging:
#  level:
#    com.tena.untact2021.dao: DEBUG
  config: classpath:logback-spring.xml

custom:
  fileDirPath: /2021/untact2021-file
  logging:
    dir: log
    level: INFO