server:
  port: 8021

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3308/untact2021?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
#     Log4j2 JDBC SQL Logger 출력
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3308/untact2021?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
    username: untact2021
    password: 123456A@

mybatis:
  # mybatis 매핑 type을 짧게 쓰기 위한 설정
  type-aliases-package: com.tena.untact2021.dto
#  mapper-locations:
#  - classpath:mybatis/mapper/*.xml

logging:
#  level:
#    com.tena.untact2021.dao: DEBUG
  config: classpath:logback-spring.xml

custom:
  logging:
    dir: log
    level: INFO